### ISSUE TITLE
From lib import DLL_SELECTION

### ISSUE THREAD

**Issue by Jiadalee** [kLabUM/storm-swarm#1]
I have installed the StormSwarm package in my local PC which is Windows 7.  I run the test.environment.py in Python 2.7 but the error shows cannot import name DLL_SELECTION. Does anyone know how to fix it? I guess the swmm5.py might not be compatible here.

![image](https://user-images.githubusercontent.com/30839207/51858045-0225b880-22f1-11e9-85ca-ebb343288484.png)

**Comment by abhiramm7** [comment]
Can you try it now ? Also you might want to upgrade to python 3.6 or greater.

**Comment by Jiadalee** [comment]
I upgraded my python to 3.7 just now. After I run the codes, a new error 'no module named lin' like this:

![image](https://user-images.githubusercontent.com/30839207/51860553-4ddb6080-22f7-11e9-9663-058ded22b60a.png)

**Comment by abhiramm7** [comment]
You seem to still using py2.7. Can you try now, should work..

**Comment by Jiadalee** [comment]
Yes. the test_enviroment.py and test_worker.py file work now. However,  there is an error genenrating_ensembles.py file: NameError: name 'ctrl' is not defined
![image](https://user-images.githubusercontent.com/30839207/51863268-d230e200-22fd-11e9-9bfc-0ff0dde9c991.png)

**Comment by abhiramm7** [comment]
Should be about couple of seconds.

**Comment by Jiadalee** [comment]
Oh. mine is still running with such errors output below. I have to stop it manually, otherwise, it will run forever..

![image](https://user-images.githubusercontent.com/30839207/51869777-d1547c00-230e-11e9-9864-51f9edca3122.png)

![image](https://user-images.githubusercontent.com/30839207/51869808-e8936980-230e-11e9-9aa8-5aa7b35a08bf.png)

**Comment by abhiramm7** [comment]
Can you try it python 3.6 ?

**Comment by Jiadalee** [comment]
Sure! I need some time to install some package in python 3.7 interpreters. I will update to you soon, Thanks

**Comment by Jiadalee** [comment]
Whoops! there is an error ' no module named toolkitapi' .  Isn't it a built-in function? 

![image](https://user-images.githubusercontent.com/30839207/51875888-fef7f000-2323-11e9-992d-ff11c24ed9c0.png)

**Comment by abhiramm7** [comment]
Code doesn't use it. So you should be able to run it without it.

**Comment by Jiadalee** [comment]
Oh, really? 

I comment it out but it still doesn't work. 

when I type 'pip install . ",  the stormswarm will be installed at the python 2 working directoy by default. So, I copy the installed 'stormswarm' folder to the pyhon 3 working directory. Instead of this, how can I install the 'stormswarm' in a specific location?

**Comment by Jiadalee** [comment]
Yes. I set the python 3 env and use pip to install packages after entering this env. Still some errors....
![image](https://user-images.githubusercontent.com/30839207/51961314-925f1d00-2419-11e9-967d-4c891c68f985.png)

**Comment by abhiramm7** [comment]
It’s an numpy issue. Can you try reinstalling it.

**Comment by Jiadalee** [comment]
Yes

**Comment by Jiadalee** [comment]
I found the key problem is that the sys path is different from the third-party package importing path ...

**Comment by abhiramm7** [comment]
Couple of things:
1. You seem to still using python 2, might want to update it to python 3
2. Multiprocessing is for running a bunch of simulations in parallel. Python doc pages mention that there might be few differences in how multiprocessing is done on a unix(which this code is tested on) and windows (https://docs.python.org/3.6/library/multiprocessing.html). If you are willing to port the code to windows, it could be a good addition. Again it is just two lines in current code, so might be a easy port. 
3. You can still use the code without using multiprocessing, you can just use the environment class and worker function.

**Comment by Jiadalee** [comment]
Ok, thank you for the suggestion, I will try this in my Desktop.

At the current stage, I have compiled storm-swarm to the Linux system for the high-performance computing. It can run in Linux system now.  However, I don't know what is the output for test_worker.py and test_environment.py. Do you have another simple script for testing which I can use to get some plots or data？

**Comment by abhiramm7** [comment]
test_environment.py and test_worker.py are the unit testing files, they test the ensemble runs. They are not intended to generate any output, though you can use the code for generating plots.
